### ISSUE TITLE
Storybook for component library

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-web#1437]
**Is your feature request related to a problem? Please describe.**

As our component library and platform functionality grows, we need an easier way to visualize our components for both designers and developers.

**Describe the solution you'd like**

We can setup [Storybook](https://storybook.js.org/) for frontend repo. We can start with running Storybook locally, then push the static version it to s3 and serve it via matters url if needed.

**Comment by Ginhing** [comment]
Hi, just mention it the PR is ready. Feel free to let me know if there is any problems 😀

**Comment by guoliu** [comment]
@Ginhing the PR looks good! Are you able to merge it in?

**Comment by Ginhing** [comment]
Oh, I assume owner or maintainer will merge it and I have no permission to merge at the same time.

**Comment by devformatters** [comment]
Nice work. Close it. 💪🏻
