### ISSUE TITLE
Edit article content

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-web#1528]
Restricted to 50 characters. Blocked by: https://github.com/thematters/matters-server/issues/1495 https://github.com/thematters/matters-server/issues/1496

![image](https://user-images.githubusercontent.com/8460804/93963887-25e21180-fd13-11ea-8cf4-7f5036dd050d.png)

**Comment by devformatters** [comment]
Here is the comparison of current publish and possible revise flows.

![flow](https://user-images.githubusercontent.com/34237112/96858041-56dc7000-1492-11eb-939b-769cab72c099.png)

**Comment by devformatters** [comment]
After couple rounds of discussion, we decided to use the similar UI/UX styles of publishing article for revising.
