### ISSUE TITLE
A / B group data confusion (possibly due to CDN)

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-web#1602]
https://mattersnews.slack.com/archives/GA0R09FHN/p1603549134000100

Some thoughts:
Sounds the error happens during SSR. So API server could be caching correctly, and CDN is not.

**Comment by Carolusian** [comment]
**Observed:**
If the user logged in as a ***b group** user* using chrome or safari on iOS, it is normal that he can view group b content. However, after he closed, and then re-open the browser. He will not be able to see b group content.

**Reason**:
`__user_group` cookie is deleted when user closed the browser.

**Comment by Carolusian** [comment]
https://github.com/thematters/matters-server/pull/1575
