### ISSUE TITLE
Position of bottom toolbar in article page is wrong

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#1603]
Position of bottom toolbar in article page is wrong, and sometimes it's in the middle of page or disappeared. It might only occurred on iPad.

![screen](https://user-images.githubusercontent.com/34237112/97403088-bc1ae000-192e-11eb-9ec0-ff2ec0497444.jpg)

**Comment by devformatters** [comment]
Users couldn't reproduce bug about toolbar is floating in the middle page. So, this issue will only focus on problem of editor bottom toolbar.

@proformatters Please arrange testing.

**Comment by proformatters** [comment]
Bugs fixed successfully on desktop, iPhone, and iPad. No toolbar floating in the process of test.
