### ISSUE TITLE
Add tag management policy in Community Regulation

### ISSUE THREAD

**Issue by proformatters** [thematters/matters-web#1616]
![image](https://user-images.githubusercontent.com/47885618/98670292-7bd74b00-238d-11eb-9410-52f34ea6bdf3.png)

8. 成為公共標籤管理者 [2]，但不按照公正、客觀立場維護標籤，且拒絕交出標籤主理權。（關於公共標籤的社區討論，請點擊這裡。）

[2] 公共標籤是指創建日期在主理標籤功能上線之前（即2020年7月27日），使用這個標籤的作者數達到40人或以上的標籤。

**Comment by devformatters** [comment]
Completed.
