### ISSUE TITLE
When a user sends the 100th donation, get a badge

### ISSUE THREAD

**Issue by proformatters** [thematters/matters-web#1618]
<img width="383" alt="螢幕截圖 2020-10-21 上午7 52 32" src="https://user-images.githubusercontent.com/47885618/96656429-619fe380-1372-11eb-9597-5f75c1ac5637.png">
<img width="373" alt="螢幕截圖 2020-10-21 上午7 53 20" src="https://user-images.githubusercontent.com/47885618/96656479-7e3c1b80-1372-11eb-8cef-3954118a167b.png">

**Comment by devformatters** [comment]
There's a duplicate issue. Close it.
