### ISSUE TITLE
Icon processing pipeline

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#1628]
**Current**
1. Export as SVG from Figma to `src/components/Icon/icons`;
2. Union as single `<path>` using Sketch.app;
4. Use `viewBox` instead of `width` & `height` for size controlling;
3. Remove `fill` for color inheritance;

**New**
1. Same as above;
2. Webpack plugin to process it during dev & build time automatically;

**Comment by devformatters** [comment]
@robertu7 do we still need this?
