### ISSUE TITLE
[Web] 提升 Matters 的 Accessibility

### ISSUE THREAD

**Issue by FledgeXu** [thematters/matters-web#2158]
对不起，我不是很清楚如何用英文来写这个issue，所以就用中文写了。
这个是个非常迫切的问题，已经严重影响到了matters用户的[使用体验](https://matters.news/@dorothyto1984/%E6%95%B8%E7%A2%BC%E9%B4%BB%E6%BA%9D-bafyreig7cnjhlvnhjkrxwihtfmwzmqptjsjf4k5zh5jqusqqrkyuxxh5wy)。
对于视障人士的使用方面的支持这是个非常复杂的工程，需要在网页设计与实现的诸多环节进行努力，更需要视障朋友的实际体验与反馈才能产生改进。
我希望这个issue，能作为一个讨论如何改进Matters Accessibility的空间。

**Comment by robertu7** [comment]
感謝提出這個 Issue！

雖然 Matters 沒有專門的針對 a11y 做優化，但也會在開發過程中加入基礎的 [`aria-*`](https://github.com/thematters/matters-web/search?q=aria)，另外在 Dialog、Toast 等基礎組件中也使用 [Reach](https://reach.tech/) 作為基底。請問你在使用時是遇到哪些比較嚴重問題呢？有哪些比較系統性的改進建議嗎？

**Comment by Dorothy1984** [comment]
我是Matters的視障用戶。現時Matters的部份功能或資訊只有圖示而沒有文字描述，視障人士使用的讀屏軟件無法讀取到。例如文章內頁顯示的總拍手數以圖示顯示，我無法讀取。文章排版的部份功能，例如以區塊分隔文章小題目，由於功能按鈕純粹以圖示表達，而且是純滑鼠操作，我也無法使用。倘若能夠增設以快捷鍵打開功能選單，或者在功能按鈕加入文字，我便能使用了。感謝@fledgexu 展開這個議題。

**Comment by FledgeXu** [comment]
@Dorothy1984 提到的问题中
> 例如文章內頁顯示的總拍手數以圖示顯示，我無法讀取。
是在这个位置的`aria-label`设置有问题，在`讚賞作品`的基础上需要加入`讚賞作品`数量的提示。
https://github.com/thematters/matters-web/blob/0349fd87cc4737ff9509ec5eae2c2d4bda9de057/src/views/ArticleDetail/AppreciationButton/AppreciateButton.tsx#L41

**Comment by FledgeXu** [comment]
@robertu7 
我昨天用VoiceOver在iPhone上测试了一下Matters，我个人觉得最严重的问题是，似乎在Voiceover下，Matters的整个Tab栏除了创作按钮之外，其他部分都无法正确读取。
不过我也是刚刚才学习使用VoiceOver，关于这点我需要 @Dorothy1984 的确认。
另外关于VoiceOver的使用，Apple 有提供相关的[教程](https://support.apple.com/guide/iphone/learn-voiceover-gestures-iph3e2e2281/ios)

**Comment by Dorothy1984** [comment]
我也試過voice over。我能找到「創作」，給作者拍手或支持的按鈕都能讀到。但「我的」底下的東西，包括個人主頁、草稿、錢包、收藏等，就一律讀不到了。因此，在手機，我連自己主頁都無法找到和進入的。

**Comment by robertu7** [comment]
@FledgeXu 如果加入一個視覺上隱藏但可以被 VoiceOver 等讀屏器讀取的 navigation 會比較方便、改動也比較少嗎？

**Comment by FledgeXu** [comment]
@robertu7 关于Tab栏的问题，我也没什么好的想法，需要更多的研究。

**Comment by Dorothy1984** [comment]
今天回到家，我發現拍手數已經在網頁版的Matters毞被我的NVDA讀屏軟件讀到了。非常感謝你們的幫忙！辛苦你們了！

**Comment by Dorothy1984** [comment]
不好意思：昨晚明明能夠在讚賞作品按鈕旁邊看見讚賞數，但今天打開Matters，讚賞數又不顯示了，為何會這麼不穩定呢？

**Comment by FledgeXu** [comment]
@Dorothy1984 看起来新功能已经合并到正式版的代码里了，可能是matters官方发现有什么问题，回滚了部署中的代码？你可以先等等看。

**Comment by Dorothy1984** [comment]
非常感謝。我後來再重新啟動電腦再次打開網頁，又能看見了。不過我上馬特市網頁超過半年，也會偶然發現一時上到的是舊版頁面，一時又上回新版頁面，我也不知道是什麼原因。希望日後能穩定一點就好了。

**Comment by Dorothy1984** [comment]
大家好：我最近在Matters開了圍爐，但我看見「圍爐」內的「新增作品」菜單，只有不上鎖的選項。請你們替我檢查一下，上鎖的按鈕又是否只有圖像呢？謝謝。

**Comment by devformatters** [comment]
Close it since there's a PR to the problem.
