### ISSUE TITLE
Add `.nvmrc`

### ISSUE THREAD

**Issue by FledgeXu** [thematters/matters-web#2161]
**Is your feature request related to a problem? Please describe.**
When I'm working on #2159, I found that the node version of this project is missing.

**Describe the solution you'd like**
Add a `.nvmrc` file in project and then people can use `nvm use` to get right node version.
It's pretty simple, just need to run `node -v > .nvmrc`
**Describe alternatives you've considered**
Add the node version to `readme.md`.

**Comment by robertu7** [comment]
It's good to have `.nvmrc` though we have defined `node` & `nvm` versions on `package.json`. Also, it's recommended to use Docker or GitHub Codespaces instead of local dev on your computer directly.

**Comment by devformatters** [comment]
@FledgeXu
I closed the issue since @robertu7 explained. Feel free to file issues if you have any problems and ideas.

Thank you. 🙌
