### ISSUE TITLE
Email input placeholder text doesn't translated

### ISSUE THREAD

**Issue by sinchang** [thematters/matters-web#2314]
**Describe the bug**

**To Reproduce**
1. Go to the `about` page https://matters.news/about
3. Scroll down to the bottom

**Expected behavior**
should be translated correctly

**Screenshots**

<img width="451" alt="Screen Shot 2021-11-10 at 22 30 04" src="https://user-images.githubusercontent.com/3297859/141131694-92c13300-8fee-4de9-b044-53e16b276703.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devformatters** [comment]
Close it since fixed.
