### ISSUE TITLE
[Web] - Support /@{userName}/{id}-{slug}-{mediaHash}

### ISSUE THREAD

**Issue by tx0c** [thematters/matters-web#2427]
and update the Share Dialog to include a textarea with:

```
{title} by @{authorName}
https://matters.news/@{userName}/{id}-{slug}-{mediaHash}
```

**Comment by devformatters** [comment]
design
- [figma](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=3865%3A20719)
