### ISSUE TITLE
[Web] Frontend testing framework review

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2439]

**Comment by robertu7** [comment]
We use Storybook for (some) UI components development, for component-level testing, it looks easy to with Storybook https://storybook.js.org/docs/react/writing-tests/introduction

**Comment by Jasmine-liang** [comment]
Front-end testing framework [docs](https://matterslab.notion.site/Front-end-testing-framework-research-26c3a7de4a894114b0831e4c9c31b138)
