### ISSUE TITLE
[Web] Update tag selector: tag recommendation

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2472]
tasks
- Improve tag selector component
- Add default tag recommendation into tag selector

design
- [figma](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=3631%3A18098)

**Comment by robertu7** [comment]
Based on Figma, which GraphQL queries shall be used? @tx0c @devformatters 

![image](https://user-images.githubusercontent.com/4065233/177285710-21a0cabc-9d1a-4c0a-bd2a-1ac1a2a316f5.png)
