### ISSUE TITLE
[Web] ISCN implementation

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2486]
design
- [figma](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=3986%3A21199)

**Comment by tx0c** [comment]
link with thematters/matters-server#2531
