### ISSUE TITLE
Thumbnail not showed when sharing via Douban & Weibo

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2504]
#### References
- [doc](https://paper.dropbox.com/doc/2022-05-1--BiJu5FA0mRSy0GUGjPFOTdrJAg-2qE7lZMsd6QdYmNaYTCKN)

**Comment by robertu7** [comment]
Weibo works fine on my side.

**Comment by robertu7** [comment]
stagnant for a while, feel free to reopen.
