### ISSUE TITLE
[Web] Update regex pattern for creating new tags

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2507]
tasks
- update editor in draft page
- update editor in /tags
- update editor in tag detail page

refs
- [doc](https://paper.dropbox.com/doc/Matters--Bijv2PhAusvor8gQ4jLeT4CeAg-56s32V8tZp0PHlTObapvl#:uid=856368007009447166235153&h2=3%EF%B8%8F%E2%83%A3-%E6%A8%99%E7%B1%A4%E5%89%B5%E5%BB%BA%E8%A6%8F%E5%89%87)

design
- [figma](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=4664%3A24752)

**Comment by tx0c** [comment]
to apply same changes in thematters/matters-server#2658
