### ISSUE TITLE
[Web] Update all tags page UIs

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2551]
tasks
- [x] update feed tab from one to two types
- [x] update tag card component
- [x] add a feed on right (for preview and switch)
- [x] don't forget design mobile device 🧞‍♂️
- [x] tab & feed click tracker

design
- [figma](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=3668%3A22908)

blocked by
- [issue](https://github.com/thematters/matters-server/issues/2596)

**Comment by robertu7** [comment]
actual point consume is 8-13.
