### ISSUE TITLE
[Web] Translation disappeared when first visit of a page

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2553]
refs
- [slack](https://mattersnews.slack.com/archives/GA0R09FHN/p1656066769857909)

**Comment by ElkLeung** [comment]
目前測試環境已無此問題，再麻煩驗證看看

**Comment by devformatters** [comment]
I could not reproduce in dev env either. Mysterious fix. 🤔

@robertu7 Close it if you still could not make a repro.

**Comment by devformatters** [comment]
Close this issue cuz cannot reproduce.
