### ISSUE TITLE
[Web] Fix "Back to discover" Button spacing

### ISSUE THREAD

**Issue by Jasmine-liang** [thematters/matters-web#2567]
**Describe the bug**
![image](https://user-images.githubusercontent.com/63624438/176989330-4e9af43e-742f-4a33-b8f1-b6f9e8de87a2.png)

**To Reproduce**
Any [error page](https://matters.news/lol)

**Desktop (please complete the following information):**
 - OS: [Manjaro Linux]
 - Browser [Chrome]
 - Version [102.0.5005.61]

**Comment by xavier-kong** [comment]
Hi may I know if the issue is open? I am interested in working on it.

**Comment by xavier-kong** [comment]
@robertu7 could I get this issue assigned to me?

**Comment by robertu7** [comment]
@xavier-kong assigned.
