### ISSUE TITLE
[Web] Increase recommended author list size

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2585]
### Tasks
- [ ] Increase 5 to 15

### Screenshot
![截圖 2022-07-11 下午3 42 30](https://user-images.githubusercontent.com/34237112/178213609-7a6da4fd-a6c8-4d92-8c43-df0ec8c1989e.png)

**Comment by robertu7** [comment]
looks tiny, @devformatters is it able to hot release this issue?

**Comment by devformatters** [comment]
I have just found you finished it now. Nice work.
