### ISSUE TITLE
for SEO: announcement cover need to Responsive Image

### ISSUE THREAD

**Issue by tx0c** [thematters/matters-web#2611]
Core Web Vitals Assessment: Failed

because of multiple issues (LCP/CLS/FCP)

the top1 is Largest Contentful Paint (LCP) 5.8 s

https://pagespeed.web.dev/report?url=https://matters.news

![image](https://user-images.githubusercontent.com/49659410/180299759-8bae829f-77a0-4fc9-8ede-1ef63f7e6424.png)

Mobile Performance of Homepage is 26 (out of 100)
![image](https://user-images.githubusercontent.com/49659410/180299804-36ab60de-cffe-468b-ac7d-c697766a65a9.png)

**Comment by robertu7** [comment]
linked issue: https://github.com/thematters/serverless-file-post-processing/issues/616
