### ISSUE TITLE
[Web] URL pattern for i18n

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-web#2623]
### Tasks
- [ ] Cloudflare: adjust caching based on `__language`;
- [x] Client
  * read language from cookie;
  * SSR based on language settings (cookie, URL subpath or user language);
- [x] Server
  * inject language cookie on login;
  * remove language cookie on logout; 

### Docs 
* https://www.notion.so/matterslab/i18n-edfbade687c74c759e33072a788dddfd

**Comment by robertu7** [comment]
To cache based on cookie `__language` on Cloudflare, we have to use [custom cache key](https://developers.cloudflare.com/cache/how-to/create-cache-keys/) [0] which is an enterprise-only feature.

A workaround is we turn off all HTML pages cache with Cloudflare Page Rule.

[0] https://developers.cloudflare.com/cache/about/cache-keys
