### ISSUE TITLE
Adjust <Expandable>

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#2699]
### Description
[`<Expandable>`](https://github.com/thematters/matters-web/tree/develop/src/components/Expandable) component doesn't always work as expected. It should be fixed, or removed if data show most users didn't exceed the word count limit.

![Image](https://user-images.githubusercontent.com/4065233/184835261-f417a3f5-5c9a-47bd-a9a2-f081f37af65d.png)

![Image](https://user-images.githubusercontent.com/4065233/184835277-5b58af62-065a-49f6-89f4-0fc4fca12d65.png)

**Comment by devformatters** [comment]
@pitb2022
I've put this issue back since @polinahuang has made mockup list for this. You can check [design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=7034%3A37092) here.

**Comment by devformatters** [comment]
Since it's in release process, close it.
