### ISSUE TITLE
Redirect logged user when login in visitor's settings

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2803]
### Tasks
- [ ] Redirect user to personal settings when login in visitor settings.
( `/settings` to `/me/settings` )

**Comment by devformatters** [comment]
@robertu7 could add your solution here ? 👋🏾

**Comment by robertu7** [comment]
There is no need to handle redirection, we can move `/settings` to `/me/settings` and render current `/settings`'s view if viewer is anonymous.

Notice that `/me/*` are protected routes, we might also have to alter the `/me` and allow a whitelisted paths (`/me/settings`) to skip validation.
