### ISSUE TITLE
Animation of support feedback message

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2809]
### Tasks
- [ ] Co-op with designer to find the best solution for animation

### References
- [Design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=6562%3A41913)
- [Design: interactive prototype](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=7678%3A47778)

**Comment by Jasmine-liang** [comment]
Ref: 
- [JSON Animation - A Lightweight Solution to Increasing User Engagement](https://creattie.com/blog/json-animation)
- [Lottie for React](https://lottiereact.com/)
