### ISSUE TITLE
Avatars are not loaded

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2919]
### Tasks

- [ ] Investigate and fix the cause of avatar 404 errors
- [ ] For NFT avatar, replace OpenSea API with Alchemy API

### References

- Screenshot 1

<img width="50%" alt="screenshot" src="https://user-images.githubusercontent.com/34237112/201701393-c0097c03-b351-40f6-b879-48312d5d785d.png">

- Screenshot 2

<img width="75%" alt="screenshot" src="https://user-images.githubusercontent.com/34237112/201701670-14278c93-f78a-4271-b7c7-56281fe8ff53.png">

**Comment by Jasmine-liang** [comment]
Ref: 
[Alchemy NFT API](https://docs.alchemy.com/reference/nft-api-quickstart#alchemy-sdk-recommended)
