### ISSUE TITLE
Back behavior is not correct after clicking in tag latest feed

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2921]
### Tasks

- [ ] Fix the issue that back behavior is not working correctly after clicking couple times in tag latest feed

### References

- [Thread discussion](https://mattersnews.slack.com/archives/GA0R09FHN/p1668134856110749?thread_ts=1668065406.589319&cid=GA0R09FHN)

**Comment by robertu7** [comment]
Query string `?type=` was reset when go back to tag page
