### ISSUE TITLE
Search flow integration

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#2954]
### Blockers
* https://github.com/thematters/matters-web/issues/2950
* https://github.com/thematters/matters-web/issues/2951
* https://github.com/thematters/matters-web/issues/2952
* https://github.com/thematters/matters-web/issues/2953

### Tasks
- [ ] integration based on components and product requirements;

### References
- [Product doc](https://www.notion.so/matterslab/Search-Rework-c66bd1db9c9c49d8a5a4b22cff5244b7)
- [Design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=9500%3A47942&t=ivFcL3GEK18ReJfu-1)

**Comment by devformatters** [comment]
from @pitb2022 

New requirement: keyboard op ref: https://www.notion.so/matterslab/Search-Rework-c66bd1db9c9c49d8a5a4b22cff5244b7#10d1aa934535487d963c7a71f4072f50
