### ISSUE TITLE
Add regression tests: article

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#3079]
### Checklist
- [x] Test donation: HKD ~and LikeCoin;~
- [x] Test article mutations: appreciation, bookmark, fork (extend), pin and unpin;
- [x] Test revise article;

### Refs
- revision: https://mattersnews.slack.com/archives/C88CK7Q7L/p1673520847520339?thread_ts=1673520666.618439&cid=C88CK7Q7L
- donation: https://mattersnews.slack.com/archives/GA0R09FHN/p1673452980150929

**Comment by devformatters** [comment]
Open a new issue for LikeCoin doantion

**Comment by tx0c** [comment]
in the long term, we don't want to depend on `mediaHash`, and allow `mediaHash` be generated async
