### ISSUE TITLE
Add regression tests: article LikeCoin donation

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#3108]
### Checklist
- [ ] Test donation: LikeCoin;

### Refs
- revision: https://mattersnews.slack.com/archives/C88CK7Q7L/p1673520847520339?thread_ts=1673520666.618439&cid=C88CK7Q7L
- donation: https://mattersnews.slack.com/archives/GA0R09FHN/p1673452980150929

**Comment by robertu7** [comment]
should be postponed due to the setup difficulty with headless E2E testing
