### ISSUE TITLE
Crowdin workflow sync

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#3360]
### Tasks
- [x] Sync the current workflow of copies management
- [x] Set a better workflow

### Ref
https://matterslab.slack.com/archives/C88CK7Q7L/p1683273470856389?thread_ts=1682656947.308119&cid=C88CK7Q7L

**Comment by robertu7** [comment]
https://www.notion.so/Crowdin-101-960b7ef1f1d44c439119c416463ee9e8
