### ISSUE TITLE
Revise Notifications UI: circle

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#3381]
### Checklist 
- [ ] circle notices: `CircleNotice`, `CommentNotice.CircleNewBroadcastNotice`, `ArticleNotice.CircleNewArticle`
- [ ] retire traveloggers wallet connected and airdrop notices, but keep db records  (confirmed w/ product team)
 
### Refs
* https://www.figma.com/file/vO8f8jaz9cZo1DsAazvHWd/Matters.news-%E6%96%B0%E7%89%88%E8%A8%AD%E8%A8%88%EF%BC%88Zn%EF%BC%89?node-id=238-1706&t=Sys5GPHLWtHRm9gS-0

**Comment by devformatters** [comment]
@robertu7 I've added a new task of removing Travloggers' wallet and airdrop notices.
