### ISSUE TITLE
Toast and popup positioning problem

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#3443]
### Tasks
- [ ] Update toast and popup positioning target

### References
- [Design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?type=design&node-id=12027-48793&t=AIDwgYQF1GMH6AaE-0)
- [Thread](https://matterslab.slack.com/archives/G8877EQMS/p1683628169286199)

### Screenshots

<img width="65%" src="https://github.com/thematters/matters-web/assets/34237112/597e8a4c-3b0f-49bd-bcfc-17b9cb30391d" />

<img width="65%" src="https://github.com/thematters/matters-web/assets/34237112/bf30a897-f749-4dca-a410-35a5bd02afeb" />

**Comment by robertu7** [comment]
closed by new toast https://github.com/thematters/matters-web/issues/3524
