### ISSUE TITLE
Form conflicts using Safari autofill password

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#3501]
### References

- [Report](https://matters.canny.io/bug-reports/p/form-conflicts-with-safari-autofill-password)

**Comment by pitb2022** [comment]
1. When lazy loading is enabled for the login dialog, 1Password is unable to autofill the email and password fields.
2. 1Password works fine on the login page.
3. Browser-native autofill works fine.

**Comment by pitb2022** [comment]
ref:
https://developer.1password.com/docs/web/compatible-website-design/
