### ISSUE TITLE
Collection Bugs

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#3732]
* [x] [個人頁 - 刪除選集後，選集 Tab 的數字沒有變動](https://feedback.matters.town/bug-reports/p/tab)
* [x] [個人頁 - 修订文章cover, 代表作主题色没有更新](https://feedback.matters.town/bug-reports/p/cover)
* [x] [個人頁 - 選集排序按鈕問題](https://feedback.matters.town/bug-reports/p/b310b2)

**Comment by pitb2022** [comment]
The data refetched from the server still the old collection count after deleting the collection.
