### ISSUE TITLE
Frontend review and task breakdowns

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#3825]
### Description
Review and confirm the PRD including design, then break down frontend tasks from Stories and estimate efforts.

### References

- [design](https://www.figma.com/file/XLTES6FFpEuAVa3z0xj8mA/%E6%88%91%E7%9A%84%E5%89%B5%E4%BD%9C?type=design&node-id=250-13580&mode=design&t=EN1BaJ9WWswn92aN-0)

### Stories
- https://github.com/thematters/developer-resource/issues/263

**Comment by pitb2022** [comment]
https://github.com/thematters/matters-web/issues/3853
https://github.com/thematters/matters-web/issues/3854
https://github.com/thematters/matters-web/issues/3855
https://github.com/thematters/matters-web/issues/3856
