### ISSUE TITLE
Layout shift on expandable component

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#3827]
### Checklist
- [ ] Confirm correct implementation of user bio & comment

Also make sure fixes these :
- [ ] [Render issue](https://feedback.matters.town/bug-reports/p/bio-render)
- [ ] [Bio extend button disappeared](https://feedback.matters.town/bug-reports/p/bio-safari)
- [x] [Comment extend button at a wrong position](https://feedback.matters.town/bug-reports/p/f11b45)

also related to https://github.com/thematters/matters-web/issues/3880

### References
- [design](https://www.figma.com/file/nOzKx4pxuhhxdx1VzDJNfF/%E5%80%8B%E4%BA%BA%E9%A0%81-%26-%E9%81%B8%E9%9B%86?type=design&node-id=695%3A72373&mode=design&t=5TkboZ2SBKF408mF-1)

**Comment by robertu7** [comment]
> 目前我们的设计：
文章卡片先测量文章标题是占了一行还是两行，然后再决定摘要渲染几行
展开收合组件需要先测量文本占了多少行，然后再决定是否收起状态（若需要收起，先截断超出行数的字符，再在文本同一行追加上「展开」按钮
实现：
> 1. 按React官方流程，useLayoutEffect会在browser paint之前调用，paint之后调用useEffect，所以正常来说在useLayoutEffect里测量DOM尺寸后计算渲染的行数，是不会出现闪烁问题的
> 2. 但因为我们还有SSR，从SSR返回的页面，会首先paint一遍，然后再开始调用useLayoutEffect和useEffect，从而导致闪烁问题。
> 3. 如果关闭了SSR，动态import对应的组件，就不会有问题，但却会影响到SEO
> PS：
> 之前Robert提到直接计算字符宽度，这个方案在我们的图书封面行得通是因为封面宽度是固定的，但文章卡片和展开组件的宽度是随着用户的viewport变化而变化的，所以这个方案在宽度变化的组件是行不通的
