### ISSUE TITLE
Adjust image loading strategy

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#3914]
### Checklist
Use `fetchpriority` for LCP images:

- [x] `fetchpriority="high"` for
  * first slide of announcement;
  * first *N* feed items;
- [x] `fetchpriority="low"` for: 
  * GIF avatars;
  * rest of the slides of announcement;
  * rest of the feed items;

Progressive loading:
- For GIF image:
  - load status format (`?anim=false`) first
  - load GIF format once other prioritized resources are loaded

### Refs
* https://www.notion.so/matterslab/matters-news-4c3fe7c774ed4c939c38f49c2632891f?pvs=4#ce468d7fe17045f1b8b4ace58df2f249
* https://vaihe.com/quick-seo-tips/using-fetchpriority-with-images/
* https://github.com/thematters/developer-resource/issues/253

**Comment by tx0c** [comment]
closed in #3995
