### ISSUE TITLE
Side collection-article feed should scroll to the current article after component loaded

### ISSUE THREAD

**Issue by zeckli** [thematters/matters-web#4375]
### Description
When viewing a collection article, the side collection-article feed (if shown) should scroll to the current article once component loaded.

### Checklist
- [ ] (Client) Make current article scrolls into view;
- [ ] (Client) Lazy render side collection-article feed;
- [ ] (Server) Revise `Collection.article` and support `includeBefore`, `includeAfter`;
- [ ] (Client) Load next page of articles on scroll up or down;

### References
- [report thread](https://www.notion.so/matterslab/481cf745732c4c8b893156c995c9f988?pvs=4)

---

### Story
- https://github.com/thematters/developer-resource/issues/372

**Comment by byhow** [comment]
note: discuss with Product on what focus behavior should this be

**Comment by byhow** [comment]
Example [collections](https://matters.town/a/48fpylvebfqo?collection=Q29sbGVjdGlvbjoxNTg4)

**Comment by zeckli** [comment]
Break this issue down into tasks.
