### ISSUE TITLE
Notice of comment like

### ISSUE THREAD

**Issue by zeckli** [thematters/matters-web#4531]
### Description
- [Allow users to receive notices when someone likes their comments.](https://www.notion.so/matterslab/03358836519648628c3935d1f62ce51e?pvs=4)

### References
- [design](https://www.figma.com/design/DDOV572OhW5hpEJsEPk9tE/%E6%94%B9%E9%80%B2?node-id=193-164)

**Comment by byhow** [comment]
need to integrate with backend API once implemented
