### ISSUE TITLE
Notices of free write event

### ISSUE THREAD

**Issue by zeckli** [thematters/matters-web#4604]
### Description
- WIP

### References
- [design](https://www.figma.com/design/vDS1dPrYuM7EHTeIaA9cPs/%E8%87%AA%E7%94%B1%E5%AF%AB?node-id=908-35401&t=DQl8IDxlKNbmRcOv-1)

---

### Story
- https://github.com/thematters/developer-resource/issues/465

**Comment by robertu7** [comment]
Use OfficialAnnoncement notice instead, no need to develop. @zeckli @gary02
