### ISSUE TITLE
Update collection detail page for collection like feature

### ISSUE THREAD

**Issue by zeckli** [thematters/matters-web#4626]
### Description
To increase engagement between collection author and reader, we'll introduce collection like feature.

- [ ] Add like button and integrate API for collection like
- [ ] Update collection detail page

### References
- [design](https://www.figma.com/design/DDOV572OhW5hpEJsEPk9tE/%E6%94%B9%E9%80%B2?node-id=238-608&t=U4g1wmbztKG4YGaD-0)

**Comment by byhow** [comment]
[figma](https://www.figma.com/design/DDOV572OhW5hpEJsEPk9tE/%E6%94%B9%E9%80%B2?node-id=238-608&t=rSqkwIe4vsE4snMl-0)
