### ISSUE TITLE
Image will be deleted while typing caption in draft editor

### ISSUE THREAD

**Issue by zeckli** [thematters/matters-web#4835]
### Description
On mobile device, the image will be deleted while typing caption in moment editor

### Reference
- [report](https://matterslab.slack.com/archives/GA0R09FHN/p1725258328729649)

**Comment by robertu7** [comment]
There is no caption input on moment editor, can you give me more details and can you reproduce?

**Comment by robertu7** [comment]
cannot reproduce or already fixed
